# Generated by Django 2.0 on 2021-08-15 20:00

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import map.models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0109_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='aggregate',
            field=models.BooleanField(default=False, verbose_name='Aggregate to Site'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('HISTORY', 'Research'), ('DESCRIPTION', 'Description'), ('STORY', 'Memory'), ('NOTE', 'Note')], default='HISTORY', max_length=16),
        ),
        migrations.AlterField(
            model_name='document',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='map.Feature'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Formatted Address'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='b_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Building Name'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='b_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Building Number'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='b_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Building Type'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='basement',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='c_area',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=8, null=True, verbose_name='Conservation Area'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='extension_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Extension/Alteration 1'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='extension_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Extension/Alteration 2'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='extension_3',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Extension/Alteration 3'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='f_date',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Facade Date'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_type',
            field=models.CharField(choices=[('WHITECHAPEL_BUILDING', 'Building in Whitechapel'), ('GREATER_WHITECHAPEL', 'Building in Greater Whitechapel'), ('OPEN_SPACE', 'Open Space'), ('PLACE', 'Area or Market')], default='WHITECHAPEL_BUILDING', max_length=100, verbose_name='Feature Type'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Footprint Geometry'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='listed',
            field=models.CharField(blank=True, choices=[('NO', 'Not Listed'), ('GRADE_1', 'Grade I'), ('GRADE_2', 'Grade II'), ('GRADE_2*', 'Grade II*')], default='NO', max_length=8, null=True, verbose_name='Listed'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='short_description',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=map.models.feature_directory_path, verbose_name='Thumbnail Image'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='thumbnail_position',
            field=models.CharField(choices=[('TOP', 'Top'), ('CENTRE', 'Centre'), ('BOTTOM', 'Bottom')], default='CENTRE', max_length=6, verbose_name='Header Image Alignment'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aggregate',
            field=models.BooleanField(default=False, verbose_name='Aggregate to Site'),
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='map.Feature'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(null=True, upload_to=map.models.feature_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='aggregate',
            field=models.BooleanField(default=False, verbose_name='Aggregate to Site'),
        ),
        migrations.AlterField(
            model_name='media',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='media',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='map.Feature'),
        ),
    ]
