# Generated by Django 2.0 on 2021-08-15 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whitechapel_blog', '0007_auto_20170407_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Event end date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='event_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Event start date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail Image'),
        ),
    ]
