# Generated by Django 2.0 on 2021-08-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitechapel_users', '0008_userprofile_had_gdpr_notificaton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='emails',
            field=models.BooleanField(default=False, verbose_name='Receive emails about your submissions from the Survey of London?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gdpr_confirm',
            field=models.BooleanField(default=False, verbose_name='Continue to receive emails from the Survey of London?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Subscribe to our newsletter'),
        ),
    ]
